### ISSUE TITLE
Sort entries during validation/build

### ISSUE THREAD

**Issue by beechnut** [18F/the-glossary#13]
I'd love to have a deterministic sorting algorithm that alphabetizes while also keeping acronyms grouped with terms.

For example:

```yaml
ATO: ...

Authority to operate: ... # term belonging to ATO

Authority: ... # no acronym, AU comes after AT (but normal sorting would have this and the above switched)

POP: ...

Period of performance: ... # terms belonging to POP, alpha-sorted

Procurement Operating Procedure: ...
```

- [ ] Step 1: Just sort the keys (sort while downcased to avoid capitalization comparison weirdness)
- [ ] Step 2: Use the more advanced algo
