### ISSUE TITLE
Cross-references should always be terms, never acronyms

### ISSUE THREAD

**Issue by beechnut** [18F/the-glossary#20]
Cross-references should always link to a term, not an acronym.

This shouldn't validate:

```yaml
...
    cross_references:
      - BAFO

BAFO:
  type: acronym
...
```

This should
```yaml
...
    cross_references:
      - Best and final offer

Best and final offer:
  type: term
...
```
